# Generated by Django 6.0.1 on 2026-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.CharField(choices=[('free', 'Free'), ('edu', 'Educational'), ('pro', 'Pro')], max_length=20, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('max_courses', models.IntegerField()),
                ('max_modules_per_course', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regeneration_limit', models.IntegerField(default=0)),
                ('certificate_access', models.BooleanField(default=False)),
                ('duration_days', models.IntegerField(default=365)),
            ],
        ),
    ]
