# Generated by Django 6.0.1 on 2026-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(unique=True)),
                ('courses_created', models.IntegerField(default=0)),
                ('modules_created', models.IntegerField(default=0)),
                ('last_reset_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usage',
            },
        ),
    ]
