# Generated by Django 6.0.1 on 2026-01-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plan'),
        ),
    ]
