# Generated by Django 6.0.1 on 2026-01-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_usage_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usage',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usage',
            name='high_score',
            field=models.IntegerField(default=0),
        ),
    ]
